// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC08CRD6P0mT8i_idUT5pZh8s6kq_xqiKI',
    appId: '1:395992923974:web:bb5a56a6607f23a24b6f47',
    messagingSenderId: '395992923974',
    projectId: 'inventory-management-app-69841',
    authDomain: 'inventory-management-app-69841.firebaseapp.com',
    storageBucket: 'inventory-management-app-69841.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAga-rt3DsclxGiNcke97RayPdkdqQP6qo',
    appId: '1:395992923974:android:d76a0609b79720c84b6f47',
    messagingSenderId: '395992923974',
    projectId: 'inventory-management-app-69841',
    storageBucket: 'inventory-management-app-69841.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaHR_AOn-87AL6WbTL8NV9LCTrNuVlqZ8',
    appId: '1:395992923974:ios:c5f16fa632b8a27f4b6f47',
    messagingSenderId: '395992923974',
    projectId: 'inventory-management-app-69841',
    storageBucket: 'inventory-management-app-69841.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaHR_AOn-87AL6WbTL8NV9LCTrNuVlqZ8',
    appId: '1:395992923974:ios:c5f16fa632b8a27f4b6f47',
    messagingSenderId: '395992923974',
    projectId: 'inventory-management-app-69841',
    storageBucket: 'inventory-management-app-69841.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC08CRD6P0mT8i_idUT5pZh8s6kq_xqiKI',
    appId: '1:395992923974:web:4fb3fbc4f662972d4b6f47',
    messagingSenderId: '395992923974',
    projectId: 'inventory-management-app-69841',
    authDomain: 'inventory-management-app-69841.firebaseapp.com',
    storageBucket: 'inventory-management-app-69841.firebasestorage.app',
  );
}
